### PR TITLE
PR-DOCX--> PDF Hyperlink or Image in Header or Footer throws Error #390

### PR DESCRIPTION
**Pull request by sammad**
This is a PR for resolution of Issue #390. Please suggest changes if any.

### CODE REVIEW

**Comment by angelozerr** [comment]
@sammad thanks for your contribution. I try to review your PR but it's very hard to see your changes https://github.com/opensagres/xdocreport/pull/391/files#diff-06b8dfcb68259065e0c4a271b5302353 Have you change some encoding or formatting settings?

**Comment by sammad** [comment]
Hello @angelozerr 
I am not sure why it was showing the format changes, however i reverted the commits and added changes without formatting changes. You can review the last commit.

**Comment by angelozerr** [comment]
@sammad I'm OK to merge your PR, but could you merge your 5 commits in 1.

**Comment by sammad** [comment]
Hi @angelozerr I merged the commits into one.

**Comment by angelozerr** [comment]
There are 7 commits now. I'm sorry with that but I would like to have clean history. If you cannot manage that, I suggest  you that you create a new PR.

**Comment by sammad** [comment]
Let me create a new PR

**Pull request closed without merging**
