### PR TITLE
SimpleImageInfo does not support JPEG/Exif format

### PR DESCRIPTION
**Pull request by Rizen59**
Here is a pull request that should fix the issue #20 
I change the SimpleImageInfo implementation by the [ImageInfo project](http://search.maven.org/#artifactdetails%7Corg.devlib.schmidt%7Cimageinfo%7C1.9%7Cjar) licenced in the public domain. This project is used in many others projects such as modeshape, a java repository implementation for persisting data.
Unit tests and licence header have been added.

### CODE REVIEW

**Comment by angelozerr** [comment]
@Rizen59 your PR seems very cool. 

@pascalleclercq do you know if "Public Domain" is compatible with our MIT license? Can we copy/paste code from "Public Domain"  to "MIT"? Thanks!

**Comment by Rizen59** [comment]
As far as I know the public domain licence can be used without any restriction as mentionned [by the wiki page](http://en.wikipedia.org/wiki/Public_domain_software). I let the author name by respect for the work he has done.

The MIT licence is a free software licence and not copyleft, meaning code from others licence can be included in. So for me there is no restriction to use it in the project, but I let you confirm that ;).

**Comment by angelozerr** [comment]
> The MIT licence is a free software licence and not copyleft, meaning code from others licence can be included in. So for me there is no restriction to use it in the project, but I let you confirm that ;).

Thanks @Rizen59 for your info. I would like just that @pascalleclercq check that to have none problem.

**Comment by Rizen59** [comment]
No problem ;)
As this fix is necessary for my project, can I release a 1.5.1 version for my own use (and not deployed) ? If yes how can I do it simply ?

**Comment by angelozerr** [comment]
@Rizen59 as soon as we will accept this PR, it will rebuild XDocReport and 1.0.6-SNAPSHOT will be available. Please wait for @pascalleclercq

**Comment by angelozerr** [comment]
Thanks @pascalleclercq  and @Rizen59 for your work!

**Pull request merged**
