### PR TITLE
Feature/upgrade itext5

### PR DESCRIPTION
**Pull request by blagae**
An upgrade to iText 5.5.7 for the itext5 plugin, as discussed earlier in #63 . This fixes a failing test, and opens the door for writing an ExtendedCompareTool for content comparison of PDF files, as discussed in #64

### CODE REVIEW

**Comment by blagae** [comment]
Apparently, iText 5.5.7 hasn't been released to Maven Central yet, so I was too early :-)

Can I (or you) retrigger the build process once 5.5.7 is available ? Or will I need to create a new PR ?

**Comment by angelozerr** [comment]
I have restarted the build. 

@blagae perhaps it should be better that you become a XDocreport contributor?

@pascalleclercq what do you think  about that?

**Comment by angelozerr** [comment]
Build was OK, thanks @blagae !

**Comment by angelozerr** [comment]
Cloudbee build failed https://opensagres.ci.cloudbees.com/job/xdocreport/fr.opensagres.xdocreport$fr.opensagres.xdocreport.itext5.extension/691/changes

@pascalleclercq could you see this problem please when you will hav etime? Thanks!

**Pull request merged**
