### PR TITLE
fix the bug of npe of new doc;

### PR DESCRIPTION
**Pull request by zzt93**
- fix the NPE bug of added test case
- add test case

### CODE REVIEW

**Comment by angelozerr** [comment]
Thanks @zzt93 !

**Comment by zzt93** [comment]
By the way, when will release 2.0.1 be published to maven repo?

**Comment by angelozerr** [comment]
@pascalleclercq what do you think?

**Comment by pascalleclercq** [comment]
Will do It before the end of June.

**Pull request merged**
