### PR TITLE
Added support for background images in odt - pdf conversion.

### PR DESCRIPTION
**Pull request by pensionarchitects-ben**
Added support for background images in odt - pdf conversion.

### CODE REVIEW

**Comment by angelozerr** [comment]
It seems that it's a cool feature. Could you add a sample in your sample (Junit) please with a backround image (see https://github.com/opensagres/xdocreport/blob/master/thirdparties-extension/org.odftoolkit.odfdom.converter.pdf/src/test/java/org/odftoolkit/odfdom/converter/core/AbstractODFDOMConverterTest.java).

Is it possible to do the same thing for iText5 please?

**Comment by pensionarchitects-ben** [comment]
I could add some unit tests, and I can try to add it for IText5 (can not get IText5 to work atm), the code should be the same. 

Currently there are still some limitations on this:
  - only 1 background image can be added
  - it will be added on every page.
  - opacity is not supported

These things will probably not be for the first few days though. But I'll keep you updated.

Btw is there a way to see when a new page is started (Not only page breaks) couldn't find this but maybe you know.

**Comment by pensionarchitects-ben** [comment]
Fixed a few minor bugs
* Images with resolutions higher or lower than 72dpi now work correctly    
* When an image is added, when opening the pdf, the pdf no longer asks to be saved

Known limitations
* Only 1 background image can be added
* This image will be added on every page
* Opacity is not supported

Things that should be done
* Add a sample in JUnit
* Add itext5 support

**Comment by angelozerr** [comment]
Many thanks @pensionarchitects-ben !

**Pull request merged**
