### PR TITLE
Issue #238 - Update to Velocity 2.0

### PR DESCRIPTION
**Pull request by instagibb**
Quick upgrade to Velocity Engine 2.0

### CODE REVIEW

**Comment by angelozerr** [comment]
Many thanks @instagibb ! But my fear is that XDocReport users will have trouble if they wish to use old Velocity. It should b every cool if we could support old and new Velocity version. But I don't know if Velocity 2 is a lot of used?

**Comment by instagibb** [comment]
@angelozerr yes I guess that is a valid concern with any library upgrade. Velocity Engine 2.0 should be a drop in replacement for most users of Velocity Engine 1.7 as the [upgrade guide](http://velocity.apache.org/engine/2.0/upgrading.html) is quite simple. 

I thought it would be worth submitting this PR (as we are using Velocity 2.0 and XDocReport) but understand if it is not the direction you want to take

**Comment by SuperPat45** [comment]
Velocity 2 is NOT just a drop-in: https://velocity.apache.org/engine/2.0/upgrading.html

I have almost one hundred template and some client can make their own template and I am unable to test all of the with velocity 2.
So I think we must keep the Velocity 1.7 compatibility in addition to version 2 and allow to select version when loading template with:

return XDocReportRegistry.getRegistry().loadReport(in, TemplateEngineKind.Velocity, false);
// or for new templates:
return XDocReportRegistry.getRegistry().loadReport(in, TemplateEngineKind.Velocity2, false);

**Comment by instagibb** [comment]
When I said "drop-in" I meant minimal work for xdocreport to upgrade. Of course there will be ramifications for client written templates. The main driver behind this upgrade is that any project using Velocity 2.0 along with xdocreport will now also have Velocity 1.7 on the class path. Managing two versions of libraries is frustrating within a maven architecture

Obviously this should be managed as any library upgrade that incorporates breaking changes would be. Giving maintainers time to plan for upgrade/communicate with stakeholders etc. 

For example
- Announced on a roadmap?
- Deprecation warnings
- Upgrade

**Comment by uded** [comment]
I think approach presented by @SuperPat45 is a correct one. Can be easily done and extended in the future, although might make dependency management a bit annoying. @instagibb, maybe an easy (well, sort of) change to use that approach?

**Comment by SuperPat45** [comment]
Better dependency management would be nice to not to have to include Freemarker and the base converter jar if wee don't use it.

**Comment by angelozerr** [comment]
> Better dependency management would be nice to not to have to include Freemarker and the base converter jar if wee don't use it.

You should not need to include Freemarker, no?

**Comment by SuperPat45** [comment]
> You should not need to include Freemarker, no?

You need to include freemarker if you want to prevent this error:

> WARN  [xdocreport.core.registry.AbstractRegistry] Error while registration of Discovery instance  fr.opensagres.xdocreport.template.freemarker.discovery.FreemarkerTemplateEngineDiscovery@3e1c1c8d
> java.lang.NoClassDefFoundError: freemarker/template/ObjectWrapper
> 	at fr.opensagres.xdocreport.template.freemarker.discovery.FreemarkerTemplateEngineDiscovery.createTemplateEngine(FreemarkerTemplateEngineDiscovery.java:42)
> 	at fr.opensagres.xdocreport.template.registry.TemplateEngineRegistry.registerInstance(TemplateEngineRegistry.java:78)
> 	at fr.opensagres.xdocreport.template.registry.TemplateEngineRegistry.registerInstance(TemplateEngineRegistry.java:42)
> 	at fr.opensagres.xdocreport.core.registry.AbstractRegistry.initializeIfNeeded(AbstractRegistry.java:76)
> 	at fr.opensagres.xdocreport.template.registry.TemplateEngineRegistry.getTemplateEngineKinds(TemplateEngineRegistry.java:118)
> 	at fr.opensagres.xdocreport.document.registry.TemplateEngineInitializerRegistry.onEndInitialization(TemplateEngineInitializerRegistry.java:166)
> 	at fr.opensagres.xdocreport.core.registry.AbstractRegistry.initializeIfNeeded(AbstractRegistry.java:87)
> 	at fr.opensagres.xdocreport.document.registry.TemplateEngineInitializerRegistry.getTemplateEngine(TemplateEngineInitializerRegistry.java:84)
> 	at fr.opensagres.xdocreport.document.registry.XDocReportRegistry.loadReport(XDocReportRegistry.java:339)
> 	at fr.opensagres.xdocreport.document.registry.XDocReportRegistry.loadReport(XDocReportRegistry.java:317)

**Comment by angelozerr** [comment]
Ok it's a warn message, but I agree with you, it's not clean

**Comment by instagibb** [comment]
Closed this PR as it obviously wasn't going to happen. I might resubmit with a Velocity 2.2 update which (as of 2.1) has backwards compatibility options which would probably cover the concerns above

**Comment by angelozerr** [comment]
@instagibb if you can provide a PR for Velocity 2 by keeping velocity 1.7, it should be very cool, thanks

**Pull request closed without merging**
