### PR TITLE
Adding support for OpenPDF

### PR DESCRIPTION
**Pull request by codecracker2014**
Change summary:
1. Adopted below method return type change in OpenPDF:
ArrayList<Chunk> getChunks()  to ArrayList<Element> getChunks() 

2. replaced itext dependency with OpenPDF.

### CODE REVIEW

**Comment by angelozerr** [comment]
It's very hard for me to find time to review this PR, anybody could review it please?

**Comment by andreasrosdal** [comment]
This looks great.

Maybe update to OpenPDF 1.3.18, then this can be merged.

**Comment by codecracker2014** [comment]
@angelozerr, @andreasrosdal i'll be updating OpenPDF dependency to 1.3.18

**Comment by codecracker2014** [comment]
@andreasrosdal I noticed #387 was logged for OpenPDF support, which one should be merged? Your comment is also there for merge.

**Comment by andreasrosdal** [comment]
They  look mostly the same. This one looks fine.

**Comment by codecracker2014** [comment]
@andreasrosdal I've updated OpenPDF dependency to 1.3.18

**Comment by andreasrosdal** [comment]
@codecracker2014 Awesome! I hope this can be merged now!

**Comment by codecracker2014** [comment]
Updated pull request with required changes.
Change summary:
1. Reverted changes done in existing itext extension.
2. Created OpenPDF extension(fr.opensagres.xdocreport.openpdf.extension).
3. Created OpenPDF based Converters.
    fr.opensagres.poi.xwpf.converter.pdf.openpdf, fr.opensagres.odfdom.converter.pdf.openpdf
4. Added OpenPDF related changes.
5. renamed package names in OpenPDF extension and convertors.

**Comment by codecracker2014** [comment]
@angelozerr, @andreasrosdal  this pull request can be merged now.

**Comment by andreasrosdal** [comment]
This looks excellent! I hope it can be merged now.

**Comment by angelozerr** [comment]
Thanks @codecracker2014 !

**Comment by janilein** [comment]
Is there somewehere an example maybe that explains how to use the added OpenPDF support?

**Comment by codecracker2014** [comment]
@janilein you can refer wiki for itext only few dependencies needs to be updated to use OpenPDF
Wiki link: https://github.com/opensagres/xdocreport/wiki/XWPFConverterPDFViaIText
Use below dependencies:
`
<artifactId>fr.opensagres.xdocreport.openpdf.extension</artifactId>
<artifactId>fr.opensagres.poi.xwpf.converter.pdf.openpdf</artifactId>
`

**Comment by janilein** [comment]
@codecracker2014 Thank you for the information, really appreciated! In order to use it via maven we should build the jars ourselves? I can't find the 2.0.3-SNAPSHOT in the central maven repository.

**Comment by fahadmaq007** [comment]
@angelozerr When can we expect the 2.0.3 (SNAPSHOT) to be published to central maven repo?

cc @codecracker2014

**Pull request merged**
