### PR TITLE
 Change strategy of range annotation processing.

### PR DESCRIPTION
**Pull request by mgolebsk**
All inner structure will be pass to new file, but no content inside them. This strategy
protects xml structure, but no inner content of annotation ragne will be printed. It is tested on several real libre office documents.

### CODE REVIEW

**Comment by mgolebsk** [comment]
Any news about merge?

**Comment by angelozerr** [comment]
> Is anyone looking into this project and PRs?

I try it but it's very hard for me to find time. PR is merged. 

Thanks @mgolebsk !

**Comment by uded** [comment]
@angelozerr, maybe get some co-maintainer? We all struggle between open source and work, maybe someone can help you out? :-)

**Comment by angelozerr** [comment]
Any contribution are welcome! If someone want to contribute more than me, I'm opened to give rights. I would like just check before that guys who want to contribute have a good skills in Java to avoid breaking XDocReport.

**Comment by mgolebsk** [comment]
In my opinion, it is better when only one person (eg you) has rights to control project :)

**Comment by angelozerr** [comment]
My main problem is that I'm working on another opensource project, and I have not time to work on XDocReport. When PR are little and there are tests, I can review it, otherwise it's to difficult for me.

**Comment by mgolebsk** [comment]
So, it is simple, just refuse PR without tests of new functionality.

**Comment by angelozerr** [comment]
Indeed it's rules that I'm following.

**Pull request merged**
