### PR TITLE
Feature/leading

### PR DESCRIPTION
**Pull request by blagae**
Original value for originMultipliedLeading was null, which leads to overlaps for larger font sizes if there is no spacingAfter, and also other spacing problems.

In the new situation, this leading parameter is defaulted to 1 for all possible cases. This is consistent with the ODF tools and seems to work to satisfaction.

### CODE REVIEW

**Comment by angelozerr** [comment]
Thanks @blagae! is it possible to add a new docx in our test please. thanks!

**Comment by blagae** [comment]
Do you have some sort of framework for checking PDF files ? The only way to guarantee that this works is to check, either visually or by analyzing the PDF's content stream, whether the lines in the resulting PDF overlap or not.

**Comment by angelozerr** [comment]
> Do you have some sort of framework for checking PDF files ? 

No -( It's a big problem. An idea that I had, it was to compare stream (expected PDF compare to generated PDF from teh converter) like http://stackoverflow.com/questions/4245863/fast-way-to-compare-inputstreams

If we do that, we will see which generated PDF changes when test throws errors. We will able to check that the new render is correct and add the new generated PDF to the JUnit. What do you think about this idea?

If you like this idea and you have time to do that, it should be fantastic.

**Comment by blagae** [comment]
Well there are several ways to do this. The more dynamic ones I know involve using iText 5 to analyze the PDFs, and I am willing to develop something that would do a comparison of PDF files. We already have such things in the test framework of the iText 5 core library, so the effort would be minor. Our current tools use GhostScript for visual comparison, an AGPL library that also requires a build parameter in the Maven build.

The problem is: if you want this functionality for the iText 2  as well, then this is where we might get into trouble with the license terms ... If I write a test framework with iText 5, and I or someone else "port" it to iText 2, then that is a derivative work. Moreover, GhostScript can't be used unless the whole iText 2 plugin is also released under the AGPL - which is, I can imagine, to be avoided.

**Comment by blagae** [comment]
The iText SCM tree apparently has a sense of humour. The signature for the CompareTool constructor has changed between iText 5.4.1 and now, so I won't be able to build a solution extending CompareTool that works now and will also work after the upcoming pull request for #63 (after iText release 5.5.7).

**Comment by angelozerr** [comment]
@pascalleclercq what do you think about that?

**Comment by pascalleclercq** [comment]
Hi,

I try to reformulate just to be sure I understand well.

@blagae you provide a patch for an improvement for the PDF converter.

@angelozerr suggests you provide some tests to prove everything work as expected.

@blagae you suggest a tool that rely on iText 5 and you suppose there will be a licensing issue with iText 5, right ?

I don't think there will be a licensing issue as long as we rely only on a <dependency> (in the pom.xml) as long as we don't bundle the iText lib with our libs.

A PDF comparaison toolkit is more than welcome and will probably enables us nice improvements.

@blagae @angelozerr can you confirm I am right ?

**Comment by blagae** [comment]
Before I react to your statements: I'm not an expert on license terms etc. I said the things I said mainly to make sure we're treading carefully, because it's not my intention to cause any licensing trouble for this project. If anything I said before was incorrect or misguided, please blame it on this ignorance and attempt to prudence.

That being said, it was my understanding that the usage of iText in any plugin for XDocReport requires that plugin, and any users of it, to adhere to an LGPL or AGPL license. I also interpreted that to be one of the reasons that the iText modules are released as plugins. This modular structure stops the GPL-type ['virus'] ( https://en.wikipedia.org/wiki/Viral_license ) from spreading to the whole project. Again, if I'm wrong, you can correct me !

Under this reasoning, a PDF inspection tool based on iText 5 would also require the modules that use it to adhere to the AGPL. Of course, this is not a problem for the iText 5 plugins. I only wanted to warn you that, as far as I can see, an iText 5 testing tool can't be used in the iText 2 plugin without losing its 'advantage' of being released under the LGPL.

If the PDF testing tool I'd write is only used for the iText 5 plugins, then of course there is indeed no licensing issue.

**Comment by angelozerr** [comment]
@blagae! even if in this issue we hav enot CompareTools, is it possible to add a new docx in our test please. After that I will able to accept your PR. Thanks!

**Comment by blagae** [comment]
Done !

**Comment by angelozerr** [comment]
Great! Many thanks @blagae !

**Pull request merged**
