### PR TITLE
Upgrade to Jakarta EE 9

### PR DESCRIPTION
**Pull request by kevinleturc**
Hello,

We are currently upgrading our application to Jakarta EE 9 and we would like to upgrade the xdocreport library to support the Jakarta namespace change.

I just did the pom and java changes, let me know if there's something else to do, like the library version for instance.

### CODE REVIEW

**Comment by kevinleturc** [comment]
Hello @angelozerr, @pascalleclercq , any thoughts on this?

**Comment by kevinleturc** [comment]
I updated the commit in order to run the GitHub Action on my fork, everything succeed https://github.com/kevinleturc/xdocreport/actions/runs/9482076272/job/26126196742.

**Comment by angelozerr** [comment]
Sorry @kevinleturc it is hard for me to work on Xdocreport project today.

Your PR looks good, if CI build is working we can merge it.

**Comment by angelozerr** [comment]
Thanks @kevinleturc !

**Comment by kevinleturc** [comment]
> Thanks @kevinleturc !

Thanks you for the merge!

Do you now when you'll release the project?
I can help if needed.

**Comment by angelozerr** [comment]
@pascalleclercq when you will have time, could you create the release, thanks!

> Do you now when you'll release the project?

I don't know, when @pascalleclercq will have tile to do that.

> I can help if needed.

@pascalleclercq and me we have no time to work on XDocReport, but the project lives thanks to the contributions of the community. If someone wants to become a commiter and will be more active than us, it should be very fantastic.

**Comment by pascalleclercq** [comment]
@angelozerr @kevinleturc  Release 2.1.0 has been uploaded to central maven repo 🥳

**Comment by angelozerr** [comment]
Thanks so much @pascalleclercq !

**Pull request merged**
