### PR TITLE
#384 Unordered list is shown ordered (Freemarker / Docx)

### PR DESCRIPTION
**Pull request by sdahlberg**

### CODE REVIEW

**Comment by brett-walker** [comment]
Any progress on this PR. I'm hitting the same problem. I'm using the suggested ugly hack from #384

**Comment by brett-walker** [comment]
Could do with a rebase and push. It might get a better response after the build has now been fixed.

**Comment by angelozerr** [comment]
> Could do with a rebase and push. It might get a better response after the build has now been fixed.

Indeed since @brett-walker have fixed the build, now we will be more confident to accept PR by checking that there are no break. 

Please rebase your PR and if everything is OK, I 'm good to merge it.

**Comment by sdahlberg** [comment]
I've updated the PR

**Comment by angelozerr** [comment]
Thanks @sdahlberg !

**Pull request merged**
